#!/bin/bash
#
# Automatically adds branch name and branch description to every commit message.
#
current_branch=$(git rev-parse --abbrev-ref HEAD)
currentURL=$(git config --get remote.origin.url)
shopt -s nocasematch


if [[ $currentURL =~ (MDLWARE-|FP-) ]] 
then
   #Fuel POS engineers don't like abbreviations
   NAME=$current_branch
else
   #other teams are happier with shortened tags for issue branches
   NAME=$(echo $current_branch | sed -E 's/(.*[a-z,A-Z]*\/[0-9,a-z,A-Z]*(\.[0-9]{2}\.[0-9]{7}|\-[0-9]+)).*$/\1/')
fi
DESCRIPTION=$(git config branch."$NAME".description)

echo "[ $NAME ] : ""$(cat $1)" > "$1"
if [ -n "$DESCRIPTION" ] 
then
   echo "" >> "$1"
   echo $DESCRIPTION >> "$1"
fi 